adding footer
TobySuch/Shifter pull request #175
Opened 2023-06-20 10:44 UTC by OsafAliSayed

I have added the footer 

before:
![image](https://github.com/TobySuch/Shifter/assets/99737087/b9404af9-4c2d-4d82-9fdf-97fc46e79d08)
after:
![image](https://github.com/TobySuch/Shifter/assets/99737087/edc9909b-373f-47f8-bc62-e9f5fc3b86ea)

2023-06-20 18:25 UTC, TobySuch requested changes
Thanks! This is a great start, and I'm sorry the ticket was quite brief. I think the footer can be simplified down though with the following changes:
- Remove the `Links` heading
- On the left side just have the copyright notice
- On the right side just a link to the Github page. I think the text can just be an SVG Invertocat Github logo and the word `Source` next to it. You can grab the SVG from [here](https://github.com/logos) and embed it into the HTML directly.

Thanks!

2023-06-20 18:25 UTC, TobySuch commented on shifter/theme/templates/base.html
> +            © 2021 Copyright:
Can you change this to 2023 please

2023-06-20 20:13 UTC, OsafAliSayed commented
did the changes as asked
before: 
![image](https://github.com/TobySuch/Shifter/assets/99737087/5862cdb1-49bd-42d6-b36e-aee3cfc5e912)
after:
![image](https://github.com/TobySuch/Shifter/assets/99737087/73b10058-209c-40b5-822a-144bcc128101)

2023-06-20 20:41 UTC, TobySuch requested changes
Thanks, couple more changes to make the footer appear at the bottom of the page.

2023-06-20 20:41 UTC, TobySuch commented on shifter/theme/templates/base.html
> +<body class="font-sans leading-normal tracking-normal bg-white">
Can you change the body classes to the following:
```
<body class="flex flex-col font-sans leading-normal tracking-normal bg-white h-screen">
```

This is to make the footer appear at the bottom

2023-06-20 20:41 UTC, TobySuch commented on shifter/theme/templates/base.html
> +    <div class="container mx-auto mt-10">
Can you add the `flex-grow` class to this div:
```
<div class="container mx-auto mt-10 flex-grow">
```
to make the footer fix to the bottom of the screen.

2023-06-20 23:25 UTC, TobySuch commented
I've moved the base.html file in #177 so you will need to rebase/merge - sorry!

2023-06-21 07:50 UTC, TobySuch approved these changes
Thanks for the contribution, really appreciate it!

2023-06-21 07:52 UTC, merged